/*
 * This file was automatically generated by EvoSuite
 * Mon Dec 01 13:33:13 GMT 2025
 */

package com.nudt.demo.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.nudt.demo.enums.BusinessType;
import com.nudt.demo.model.BaseParam;
import com.nudt.demo.model.DeepNestedParam;
import com.nudt.demo.model.NestedParam1;
import com.nudt.demo.model.NestedParam2;
import com.nudt.demo.service.FinalBusinessService;
import com.nudt.demo.service.Layer1Service;
import com.nudt.demo.service.Layer2Service;
import com.nudt.demo.service.Layer3Service;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class FinalBusinessService_ESTest extends FinalBusinessService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BusinessType businessType0 = BusinessType.TRANSFER;
      FinalBusinessService finalBusinessService0 = new FinalBusinessService((Layer3Service) null, businessType0, (DeepNestedParam) null, (List<String>) null, 0.0, (-3651));
      finalBusinessService0.getWhiteList();
      assertEquals(0.0, finalBusinessService0.getFeeRate(), 0.01);
      assertEquals((-3651), finalBusinessService0.getVersion());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BusinessType businessType0 = BusinessType.PAYMENT;
      DeepNestedParam deepNestedParam0 = new DeepNestedParam((String) null, 1824L, false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("");
      FinalBusinessService finalBusinessService0 = new FinalBusinessService((Layer3Service) null, businessType0, deepNestedParam0, linkedList0, (-3093.912430979121), 0);
      finalBusinessService0.getWhiteList();
      assertEquals(0, finalBusinessService0.getVersion());
      assertEquals((-3093.912430979121), finalBusinessService0.getFeeRate(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Layer3Service layer3Service0 = new Layer3Service((Layer2Service) null, true);
      BusinessType businessType0 = BusinessType.PAYMENT;
      DeepNestedParam deepNestedParam0 = new DeepNestedParam(", Version: ", 2099L, true);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService(layer3Service0, businessType0, deepNestedParam0, linkedList0, 2099L, 0);
      int int0 = finalBusinessService0.getVersion();
      assertEquals(0, int0);
      assertEquals(2099.0, finalBusinessService0.getFeeRate(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BusinessType businessType0 = BusinessType.PAYMENT;
      Layer1Service layer1Service0 = new Layer1Service("", businessType0, (-2954));
      Layer2Service layer2Service0 = new Layer2Service(layer1Service0, (BaseParam) null);
      Layer3Service layer3Service0 = new Layer3Service(layer2Service0, true);
      DeepNestedParam deepNestedParam0 = new DeepNestedParam("", (-1664L), false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService(layer3Service0, businessType0, deepNestedParam0, linkedList0, (-2954), (-2954));
      int int0 = finalBusinessService0.getVersion();
      assertEquals((-2954.0), finalBusinessService0.getFeeRate(), 0.01);
      assertEquals((-2954), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BusinessType businessType0 = BusinessType.PAYMENT;
      DeepNestedParam deepNestedParam0 = new DeepNestedParam("r", 1L, false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService((Layer3Service) null, businessType0, deepNestedParam0, linkedList0, 1L, 1003);
      finalBusinessService0.getLayer3Service();
      assertEquals(1.0, finalBusinessService0.getFeeRate(), 0.01);
      assertEquals(1003, finalBusinessService0.getVersion());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BusinessType businessType0 = BusinessType.PAYMENT;
      Layer1Service layer1Service0 = new Layer1Service("}D=<&BIP70( ", businessType0, 161);
      Layer2Service layer2Service0 = new Layer2Service(layer1Service0, (BaseParam) null);
      Layer3Service layer3Service0 = new Layer3Service(layer2Service0, true);
      DeepNestedParam deepNestedParam0 = new DeepNestedParam("}D=<&BIP70( ", 161, true);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService(layer3Service0, businessType0, deepNestedParam0, linkedList0, 161, 161);
      finalBusinessService0.getLayer3Service();
      assertEquals(161, finalBusinessService0.getVersion());
      assertEquals(161.0, finalBusinessService0.getFeeRate(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BusinessType businessType0 = BusinessType.TRANSFER;
      Layer1Service layer1Service0 = new Layer1Service("", businessType0, 0);
      BaseParam baseParam0 = new BaseParam((NestedParam1) null, (NestedParam2) null, "");
      Layer2Service layer2Service0 = new Layer2Service(layer1Service0, baseParam0);
      Layer3Service layer3Service0 = new Layer3Service(layer2Service0, false);
      DeepNestedParam deepNestedParam0 = new DeepNestedParam("", 0L, false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService(layer3Service0, businessType0, deepNestedParam0, linkedList0, 0, 0);
      double double0 = finalBusinessService0.getFeeRate();
      assertEquals(0.0, double0, 0.01);
      assertEquals(0, finalBusinessService0.getVersion());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BusinessType businessType0 = BusinessType.TRANSFER;
      Layer1Service layer1Service0 = new Layer1Service("", businessType0, 0);
      BaseParam baseParam0 = new BaseParam((NestedParam1) null, (NestedParam2) null, "");
      Layer2Service layer2Service0 = new Layer2Service(layer1Service0, baseParam0);
      Layer3Service layer3Service0 = new Layer3Service(layer2Service0, false);
      DeepNestedParam deepNestedParam0 = new DeepNestedParam("", 0L, false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService(layer3Service0, businessType0, deepNestedParam0, linkedList0, 1.0, 1003);
      double double0 = finalBusinessService0.getFeeRate();
      assertEquals(1.0, double0, 0.01);
      assertEquals(1003, finalBusinessService0.getVersion());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BusinessType businessType0 = BusinessType.PAYMENT;
      Layer1Service layer1Service0 = new Layer1Service("}D=<&BIP70( ", businessType0, 161);
      Layer2Service layer2Service0 = new Layer2Service(layer1Service0, (BaseParam) null);
      Layer3Service layer3Service0 = new Layer3Service(layer2Service0, true);
      DeepNestedParam deepNestedParam0 = new DeepNestedParam("}D=<&BIP70( ", 161, true);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService(layer3Service0, businessType0, deepNestedParam0, linkedList0, 161, 161);
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      hashMap0.put("", "");
      finalBusinessService0.setExtMap(hashMap0);
      finalBusinessService0.getExtMap();
      assertEquals(161, finalBusinessService0.getVersion());
      assertEquals(161.0, finalBusinessService0.getFeeRate(), 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BusinessType businessType0 = BusinessType.TRANSFER;
      FinalBusinessService finalBusinessService0 = new FinalBusinessService((Layer3Service) null, businessType0, (DeepNestedParam) null, (List<String>) null, 0.0, (-3651));
      finalBusinessService0.getDeepParam();
      assertEquals(0.0, finalBusinessService0.getFeeRate(), 0.01);
      assertEquals((-3651), finalBusinessService0.getVersion());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BusinessType businessType0 = BusinessType.TRANSFER;
      Layer1Service layer1Service0 = new Layer1Service("", businessType0, 0);
      BaseParam baseParam0 = new BaseParam((NestedParam1) null, (NestedParam2) null, "");
      Layer2Service layer2Service0 = new Layer2Service(layer1Service0, baseParam0);
      Layer3Service layer3Service0 = new Layer3Service(layer2Service0, false);
      DeepNestedParam deepNestedParam0 = new DeepNestedParam("", 0L, false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService(layer3Service0, businessType0, deepNestedParam0, linkedList0, 0, 0);
      finalBusinessService0.getDeepParam();
      assertEquals(0.0, finalBusinessService0.getFeeRate(), 0.01);
      assertEquals(0, finalBusinessService0.getVersion());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BusinessType businessType0 = BusinessType.PAYMENT;
      DeepNestedParam deepNestedParam0 = new DeepNestedParam("", (-1595L), false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService((Layer3Service) null, businessType0, deepNestedParam0, linkedList0, (-1595L), 10);
      finalBusinessService0.getDeepParam();
      assertEquals((-1595.0), finalBusinessService0.getFeeRate(), 0.01);
      assertEquals(10, finalBusinessService0.getVersion());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Layer3Service layer3Service0 = new Layer3Service((Layer2Service) null, true);
      BusinessType businessType0 = BusinessType.PAYMENT;
      DeepNestedParam deepNestedParam0 = new DeepNestedParam(", Version: ", 2099L, true);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService(layer3Service0, businessType0, deepNestedParam0, linkedList0, 2099L, 0);
      finalBusinessService0.getDeepParam();
      assertEquals(2099.0, finalBusinessService0.getFeeRate(), 0.01);
      assertEquals(0, finalBusinessService0.getVersion());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BusinessType businessType0 = BusinessType.REFUND;
      DeepNestedParam deepNestedParam0 = new DeepNestedParam(", Version: ", 2099L, true);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.offerFirst(", Version: ");
      Layer1Service layer1Service0 = new Layer1Service(", Version: ", businessType0, 0);
      NestedParam1 nestedParam1_0 = new NestedParam1(deepNestedParam0, ", Version: ", (-10));
      NestedParam2 nestedParam2_0 = new NestedParam2(deepNestedParam0, linkedList0, 1709);
      BaseParam baseParam0 = new BaseParam(nestedParam1_0, nestedParam2_0, ", Version: ");
      Layer2Service layer2Service0 = new Layer2Service(layer1Service0, baseParam0);
      Layer3Service layer3Service0 = new Layer3Service(layer2Service0, true);
      FinalBusinessService finalBusinessService0 = new FinalBusinessService(layer3Service0, businessType0, deepNestedParam0, linkedList0, 1676.1603205, (-2258));
      // Undeclared exception!
      try { 
        finalBusinessService0.executeBusiness(", Version: ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nudt.demo.service.Layer3Service", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Layer3Service layer3Service0 = new Layer3Service((Layer2Service) null, false);
      BusinessType businessType0 = BusinessType.TRANSFER;
      DeepNestedParam deepNestedParam0 = new DeepNestedParam("krVersiJ7\nc: ", 0, false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.offerFirst("krVersiJ7\nc: ");
      FinalBusinessService finalBusinessService0 = new FinalBusinessService(layer3Service0, businessType0, deepNestedParam0, linkedList0, 0, 0);
      String string0 = finalBusinessService0.executeBusiness("krVersiJ7\nc: ");
      assertEquals(0, finalBusinessService0.getVersion());
      assertEquals(0.0, finalBusinessService0.getFeeRate(), 0.01);
      assertEquals("Order krVersiJ7\nc:  rejected (not in whiteList or service disabled)", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      BusinessType businessType0 = BusinessType.PAYMENT;
      DeepNestedParam deepNestedParam0 = new DeepNestedParam("", (-1595L), false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService((Layer3Service) null, businessType0, deepNestedParam0, linkedList0, (-1595L), 10);
      String string0 = finalBusinessService0.executeBusiness((String) null);
      assertEquals((-1595.0), finalBusinessService0.getFeeRate(), 0.01);
      assertEquals(10, finalBusinessService0.getVersion());
      assertEquals("Order null rejected (not in whiteList or service disabled)", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      BusinessType businessType0 = BusinessType.PAYMENT;
      DeepNestedParam deepNestedParam0 = new DeepNestedParam((String) null, 1824L, false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService((Layer3Service) null, businessType0, deepNestedParam0, linkedList0, (-3093.912430979121), 0);
      double double0 = finalBusinessService0.getFeeRate();
      assertEquals(0, finalBusinessService0.getVersion());
      assertEquals((-3093.912430979121), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BusinessType businessType0 = BusinessType.PAYMENT;
      DeepNestedParam deepNestedParam0 = new DeepNestedParam((String) null, 1824L, false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService((Layer3Service) null, businessType0, deepNestedParam0, linkedList0, (-3093.912430979121), 0);
      finalBusinessService0.getWhiteList();
      assertEquals((-3093.912430979121), finalBusinessService0.getFeeRate(), 0.01);
      assertEquals(0, finalBusinessService0.getVersion());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BusinessType businessType0 = BusinessType.PAYMENT;
      DeepNestedParam deepNestedParam0 = new DeepNestedParam((String) null, 1824L, false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService((Layer3Service) null, businessType0, deepNestedParam0, linkedList0, (-3093.912430979121), 0);
      finalBusinessService0.getExtMap();
      assertEquals(0, finalBusinessService0.getVersion());
      assertEquals((-3093.912430979121), finalBusinessService0.getFeeRate(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      BusinessType businessType0 = BusinessType.PAYMENT;
      DeepNestedParam deepNestedParam0 = new DeepNestedParam((String) null, 1824L, false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService((Layer3Service) null, businessType0, deepNestedParam0, linkedList0, (-3093.912430979121), 0);
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      finalBusinessService0.setExtMap(hashMap0);
      finalBusinessService0.getExtMap();
      assertEquals((-3093.912430979121), finalBusinessService0.getFeeRate(), 0.01);
      assertEquals(0, finalBusinessService0.getVersion());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      BusinessType businessType0 = BusinessType.REFUND;
      Layer1Service layer1Service0 = new Layer1Service("", businessType0, 1);
      DeepNestedParam deepNestedParam0 = new DeepNestedParam("D&DT\"y0E8G$.\"Y.+W", (-729L), false);
      NestedParam1 nestedParam1_0 = new NestedParam1(deepNestedParam0, ", Version: ", (-1332.2488582));
      LinkedList<String> linkedList0 = new LinkedList<String>();
      NestedParam2 nestedParam2_0 = new NestedParam2(deepNestedParam0, linkedList0, 1);
      BaseParam baseParam0 = new BaseParam(nestedParam1_0, nestedParam2_0, ";K[$tI;{UF!{");
      Layer2Service layer2Service0 = new Layer2Service(layer1Service0, baseParam0);
      Layer3Service layer3Service0 = new Layer3Service(layer2Service0, true);
      FinalBusinessService finalBusinessService0 = new FinalBusinessService(layer3Service0, businessType0, deepNestedParam0, linkedList0, (-729L), 1);
      int int0 = finalBusinessService0.getVersion();
      assertEquals((-729.0), finalBusinessService0.getFeeRate(), 0.01);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      BusinessType businessType0 = BusinessType.TRANSFER;
      Layer1Service layer1Service0 = new Layer1Service("", businessType0, 0);
      BaseParam baseParam0 = new BaseParam((NestedParam1) null, (NestedParam2) null, "");
      Layer2Service layer2Service0 = new Layer2Service(layer1Service0, baseParam0);
      Layer3Service layer3Service0 = new Layer3Service(layer2Service0, false);
      DeepNestedParam deepNestedParam0 = new DeepNestedParam("", 0L, false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService(layer3Service0, businessType0, deepNestedParam0, linkedList0, 0, 0);
      finalBusinessService0.getLayer3Service();
      assertEquals(0.0, finalBusinessService0.getFeeRate(), 0.01);
      assertEquals(0, finalBusinessService0.getVersion());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      BusinessType businessType0 = BusinessType.PAYMENT;
      DeepNestedParam deepNestedParam0 = new DeepNestedParam((String) null, 1824L, false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FinalBusinessService finalBusinessService0 = new FinalBusinessService((Layer3Service) null, businessType0, deepNestedParam0, linkedList0, (-3093.912430979121), 0);
      finalBusinessService0.getBusinessType();
      assertEquals(0, finalBusinessService0.getVersion());
      assertEquals((-3093.912430979121), finalBusinessService0.getFeeRate(), 0.01);
  }
}
